### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by alexandre-mbm** [guilhermelirio/arduino_rele_ethernet#1]
É usual declarar uma licença para o repositório, já que o código está "aberto".

**Comment by guilhermelirio** [comment]
Nem sei como faz isso uaUahAUHAua

**Comment by alexandre-mbm** [comment]
@guilhermelirio, foi muito bom ver seu projeto publicado aqui no GitHub!

Infelizmente eu precisei atrasar mais de 15 dias o meu retorno aqui. Percebo que nesse ínterim você elegeu a GPLv3. Por isso, hoje a abordagem que devo fazer é outra, mais adiantada.

É preciso verificarmos "se você pode" usar a GPLv3. Como?

Verificando a compatibilidade desta licença com as licenças das bibliotecas linkadas:
- SPI.h
- Ethernet.h
- ambiente de programação C do Arduino

**Comment by alexandre-mbm** [comment]
Mais leitura sobre compatibilidade com GPL:
- [Compatibilidade de licenças](https://pt.wikipedia.org/wiki/Compatibilidade_de_licen%C3%A7as) ‒ Wikipédia
- [GPL and LGPL open source licensing restrictions](http://stackoverflow.com/questions/1114045/gpl-and-lgpl-open-source-licensing-restrictions) ‒ StackOverflow
